version: '3.9'

services:
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: mydb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    stdin_open: true
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3030:8000
    environment:
      DB_CONNECTION: mongodb
      DB_HOST: database
      DB_PORT: 27017
      DB_DATABASE: mydb
      DB_USERNAME: admin
      DB_PASSWORD: admin
    depends_on:
      - database
    networks:
      - app-network

  nginx:
    image: nginx:1.21-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
      - database
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: